# Generated by Django 4.1.2 on 2022-10-27 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0002_rename_title_lyric_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="likes",
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
